# Generated by Django 5.2.7 on 2025-10-09 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_of_brith',
            new_name='date_of_birth',
        ),
        migrations.AddField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Died'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('51858b23-73df-4bab-a7f1-9d1503d7e923'), help_text='Введите UUID', primary_key=True, serialize=False),
        ),
    ]
