# Generated by Django 5.2.7 on 2025-10-09 17:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_id_language_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('63f454bc-7021-4242-8a15-b5972c5e3e22'), help_text='Введите UUID', primary_key=True, serialize=False),
        ),
    ]
