# Generated by Django 5.2.7 on 2025-10-14 12:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_bookinstance_status_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ab9eef13-c78d-4296-803b-547eb780ab21'), help_text='Введите UUID', primary_key=True, serialize=False),
        ),
    ]
