# Generated by Django 5.2.7 on 2025-10-15 13:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7ac8158c-266e-4b2a-86eb-7c05f1f989e9'), help_text='Введите UUID', primary_key=True, serialize=False),
        ),
    ]
