# Generated by Django 5.2.7 on 2025-10-27 15:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_bookinstance_id_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a1314007-05a7-42f9-b96a-d8d2ae5a8a41'), help_text='Введите UUID', primary_key=True, serialize=False),
        ),
    ]
