# Generated by Django 5.2.7 on 2025-10-27 18:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_bookinstance_borrower_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('39fa2c3f-aeaa-4300-aab0-9c741178752a'), help_text='Введите UUID', primary_key=True, serialize=False),
        ),
    ]
