# Generated by Django 5.2.7 on 2025-10-31 21:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a95d993b-be23-4129-9039-ded0e02fc212'), help_text='Введите UUID', primary_key=True, serialize=False),
        ),
    ]
